### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by luissolanodev** [bbenzikry/snazzybuddy.nvim#1]
Hey, the plugin is not loaded corretly. I managed to fix it by putting a '+' sign instead of a comma in last parameter at line 437 of snazzybuddy.lua

![image](https://user-images.githubusercontent.com/29529436/117560315-613b1180-b052-11eb-9fdd-67d790b4fe51.png)

**Comment by bbenzikry** [comment]
Thanks, this seemed to have happened due to an update to the colorbuddy repo.
I happily accept PRs in case you find anything else.
